/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Default Save": "默认存档",
    "Delete": "删除",
    "No": "否",
    "Saves": "存档",
    "Options": "选项",
    "Yes": "是",
    "Are you sure?": "你确定吗？",
    "Edit Name": "编辑名称",
    "Info": "信息",
    "Currently:": "当前:",
    "Appearance": "外观",
    "How the game looks.": "游戏看起来如何。",
    "Theme": "主题",
    "Show milestones": "显示里程碑",
    "Show TPS meter at the bottom-left corner of the page.": "在页面左下角显示 TPS。",
    "Show TPS": "显示 TPS",
    "None": "无",
    "Align modifier units": "对齐概览单位",
    "Align numbers to the beginning of the unit in modifier view.": "在概览视图中将数字与单元的开头对齐。",
    "Select which milestones to display based on criterias.": "根据标准选择要显示的里程碑。",
    "All": "全部",
    "Classic": "经典",
    "Configurable": "可配置",
    "Duplicate": "复制",
    "Mute": "静音",
    "Unmute": "播放",
    "A legion of mirrors: Tenfold divided, each division a mirror reflecting endless quiet.": "镜子军团：十重分割，每一分割都是一面镜子，反射出无尽的宁静。",
    "A small nucleus remains with you throughout resets. Each level provides +0.02n and +0.02e per tick.": "在整个重置过程中，一个小核心会一直伴随着你。 每个级别提供每tick +0.02n 和 +0.02e。",
    "A small tendon remains with you throughout resets. Each level provides +0.02i and +0.02w per tick.": "在整个重置过程中，一条小肌腱会一直伴随着您。 每个级别提供每tick +0.02i 和 +0.02w。",
    "Abort": "中止",
    "Analyze Anomalies": "分析异常情况",
    "Anomalies": "异常现象",
    "Atlas Unseen: As you gather in quiet persistence, the world shifts imperceptibly on invisible shoulders.": "看不见的阿特拉斯：当你们安静地坚持不懈地聚集在一起时，世界就会在无形的肩膀上不知不觉地发生变化。",
    "Available Prestige Points:": "可用声望点：",
    "Awakening of the Soul: In a universe of echoes, you found your voice.": "灵魂的觉醒：在共鸣的宇宙中，你找到了你的声音。",
    "Background Brightness:": "背景亮度：",
    "Cave View": "洞穴视图",
    "Celestial Division: None, breathed the light, faint and faery, of the stars, and two.": "天界：没有，呼吸着星星的微弱仙光，还有两个。",
    "Cell View": "细胞视图",
    "Cells available:": "可用细胞：",
    "Chilled Secrets: Unearthed the frozen whispers of the ice cave, a testament to the world's silent past.": "冰冷的秘密：挖掘冰洞中冰冻的低语，这是世界沉默的过去的证明。",
    "Choosing this evolution significantly affects the course of the story and will lock you out of other potential evolutions. Are you sure you wish to proceed?": "选择这种进化会极大地影响故事的进程，并将让你无法参与其他潜在的进化。 您确定要继续吗？",
    "Confluence of Fates: Eventually, all things merge into one, and a river runs through it.": "命运汇合：最终，万物融合为一，一条河流贯穿其中。",
    "Convert": "转换",
    "Crystal Excavator: The ice murmurs, a frosty sonnet in a world bereft of verse.": "水晶挖掘机：冰在低语，在一个缺乏诗意的世界里，一首冰冷的十四行诗。",
    "Dawn of Complexity: From humble beginnings to a being of greater intricacy. The protoworm emerges, a testament to evolution's silent march.": "复杂性的黎明：从卑微的开始到更加复杂的存在。 原虫的出现，证明了进化的无声前进。",
    "Discovery View": "探索视图",
    "Echo": "共鸣",
    "Eclipsed in Frost: The moon calls to the water; here, in frozen depths, you too answer.": "霜蚀：月呼水； 在这里，在冰冻的深处，你也给出了答案。",
    "Emergent Complexity: From one, many. From simplicity, complexity. The ProtoPod heralds a new chapter in solitude.": "突发的复杂性：从一到多。 从简单到复杂。 原足期 预示着孤独的新篇章。",
    "Evolve to ProtoCyst": "进化到 原包囊",
    "Evolve to ProtoGrade": "进化到 原型级",
    "Evolve to ProtoPod": "进化到 原足期",
    "Evolve to ProtoWorm": "进化到 原蠕虫",
    "Explored Terrains": "探索过的地形",
    "Feathers of Yearning: Reach toward a sky forever distant, tuning you into the unheard frequencies of a silent world.": "向往之羽：伸向永远遥远的天空，将你调到寂静世界中闻所未闻的频率。",
    "Fiery Heart: Stood before the volcano, feeling the warmth and fury of a world alive yet alone.": "火热的心：站在火山前，感受着一个充满生机却又孤独的世界的温暖和愤怒。",
    "Fragile Bonds: A connection severed. Yet in loss, resilience is born.": "脆弱的纽带：连接被切断。 然而，在损失中，韧性诞生了。",
    "Game Saved": "游戏已保存",
    "Genesis Unbound: With newfound knowledge, the first stroke is cast upon the canvas of the world.": "创世无界：凭借新发现的知识，第一笔划在世界的画布上。",
    "Heart's Anchor: You found solace, amidst solitude.": "心之锚：你在孤独中找到了慰藉。",
    "Journey's Momentum: A hundred tiles unveiled. With each step, the world becomes both larger and smaller.": "旅程的动力：一百块瓷砖揭开面纱。 每走一步，世界就会变得更大或更小。",
    "Lonely Cartographer: Use an echo to reveal the map.": "孤独的制图师：使用共鸣来显示地图。",
    "Magma Shepherd: Ten thousand days in the fire is long enough. You're going home.": "岩浆牧羊人：在烈火中一万天已经足够长了。 你要回家了。",
    "Master of Realms: Every corner of the world known, yet the heart's quest remains eternal.": "领域大师：世界的每一个角落都为人所知，但内心的追求却是永恒的。",
    "Mini-Nucleus": "迷你核",
    "Mini-Tendon": "迷你肌腱",
    "Network of Solitude: Five tendrils, each a silent cry for connection. Alone, yet ever-reaching.": "孤独之网：五根卷须，每根卷须都在无声地呼喊着联系。 孤独，却又深远。",
    "New": "新",
    "No, Wait": "不，等等",
    "Persistent Pathfinder: A thousand mysteries uncovered, yet the quest for understanding never wanes.": "坚持不懈的探路者：一千个谜团被揭开，但对理解的追求却从未减弱。",
    "Petal Pathways: Hands shape the earth, yet touch no other. The first worker takes their silent post.": "花瓣路径：双手塑造大地，但不触及其他。 第一个工人开始了他们沉默的岗位。",
    "Prestige Now": "威望现在",
    "Prestige Options": "声望选项",
    "Primal Wiggle: Unlock the mystery of movement.": "原始摆动：解开运动的奥秘。",
    "Research": "研究",
    "Reset Game": "重置游戏",
    "Reset Tutorials": "重置教程",
    "Resilience Manifested: Overcame 10 major challenges or obstacles. Every setback, a lesson; every triumph, a silent victory in the void.": "表现出韧性：克服了 10 个主要挑战或障碍。 每一次挫折，都是一次教训； 每一次胜利，都是虚空中无声的胜利。",
    "Sagan's Symphony: Somewhere, something incredible is waiting to be known.": "萨根交响曲：在某个地方，有一些令人难以置信的事情等待着我们去发现。",
    "Save Game": "保存游戏",
    "Shadows of Eons: The Earth does not need new continents, but new men.": "亿万之影：地球需要的不是新大陆，而是新人类。",
    "Silent Symbiosis: In the quiet dark, a humble luminescence. Sustenance in silence.": "沉默共生：在安静的黑暗中，发出微弱的光芒。 默默地寄托。",
    "Solara": "太阳",
    "Solara's Devotion: The falcon cannot hear the falconer; Yet love, spiraling outward, found its center.": "太阳的奉献：猎鹰听不到猎鹰人的声音； 然而，爱，螺旋向外，找到了它的中心。",
    "Solitary Sage: Alone with thoughts, the vast expanse of knowledge is both solace and torment.": "孤独圣人：独自思考，浩瀚的知识既是安慰也是折磨。",
    "Sorrow's Grip: Like anchors in a turbulent sea, your suction cups cling to an elusive, quiet stability.": "悲伤之握：就像汹涌大海中的锚一样，你的吸盘紧紧抓住难以捉摸、安静的稳定性。",
    "Soul": "灵魂",
    "Starlight Barbs: Glistening like constellations in a lonely sky, your spikes serve as both shield and spectacle.": "星光倒刺：你的尖刺就像孤独天空中的星座一样闪闪发光，既可以作为盾牌，也可以作为奇观。",
    "Subterranean Maestro: The cave becomes a labyrinth of connection, yet you remain apart.": "地下大师：洞穴变成了一个联系的迷宫，但你们仍然分开。",
    "Support on Patreon": "在 Patreon 上支持作者",
    "Tendril's Touch: You stretched out, seeking connection in a world of solitude.": "卷须之触：你伸展身体，在孤独的世界中寻求联系。",
    "Tentative Explorer: The first steps into the unknown, a mere glimpse of the vast expanse.": "尝试性探索者：踏入未知世界的第一步，只是瞥见广阔的广阔天地。",
    "Terra's Novice: Even in isolation, the world bends to will.": "泰拉的新手：即使孤立无援，世界也会屈服于意志。",
    "Terraform": "地形",
    "Theseus's Voyage: In the labyrinth of change, the string remains yet the maze is new.": "忒修斯的航行：在变化的迷宫中，绳子还在，但迷宫却是新的。",
    "Unhide": "取消隐藏",
    "v0.15": "v0.15",
    "Warmth in the Void: The fires below speak in tongues of flame, an ancient hymn sung to an empty cathedral.": "虚空中的温暖：下面的火焰用火焰的语言说话，这是一首为空荡荡的大教堂唱的古老赞美诗。",
    "Web of Yearning: You ached for touch and found no comfort.": "渴望之网：你渴望触摸却找不到安慰。",
    "Whispering Waters: In the vast silence, a murmured promise.": "水语：在浩瀚的寂静中，低声的承诺。",
    "Whispers in the Wind: Sent out 500 echoes into the void, seeking, always seeking. Every silent return is a testament to perseverance.": "风中低语：向虚空发出500个共鸣，寻找，永远寻找。 每一次默默的回归，都是坚持的证明。",
    "Wiggle": "摆动",
    "Wipe Prestige": "抹去声望",
    "Worker Assignment": "工人分配",
    "World Discovery:": "世界探索：",
    "Yes, Evolve": "是的，进化",
    "Zoom In": "放大",
    "Zoom Out": "缩小",
    "Zoom Reset": "缩放重置",
    "Grow Tendon": "长肌腱",
    "Grow Tendon ": "长肌腱 ",
    "Sense": "感觉",
    "You bristle with each new addition, a growing storm against the cosmos.": "您对每增加一个新成员，对宇宙的越来越多的风暴都感到沮丧。",
    "You feel confined, each new tendril a string that ties you to solitude.": "您会感到被限制，每个新卷须都是将您与孤独联系在一起的弦。",
    "You feel your form harden, each new tendril a fortification against the relentless emptiness.": "您会感到自己的状态变硬，每个新卷须都会防御无情的空虚。",
    "You quiver in anticipation, eager to explore new textures and horizons.": "您期待着颤抖，渴望探索新的纹理和视野。",
    "You see these appendages as instruments of touch, feeling the heartbeats of a lifeless world.": "您将这些附属物视为触摸工具，感受到无生命世界的心跳。",
    "You sense a glimmering pathway opening, a bright tunnel amid perpetual shadow.": "您会感觉到一条闪闪发光的道路开口，在永久阴影中明亮的隧道。",
    "Your tendrils reach out, brushing against the boundaries of your existence. Each new addition is a fragment of possibility, a question unanswered. What does your form say about your fate?": "您的卷须伸出来，刷在您存在的边界上。 每个新增加都是可能性的片段，这是一个未解决的问题。 您对命运有何评论？",
    "The soul radar graph is a visual representation of the soul and personality you are forging through your choices. Each decision subtly impacts gameplay, affecting evolutionary paths, narrative elements, and game mechanics. This dynamic system reflects the uniqueness of your journey, creating a personalized experience shaped by your interactions and choices.": "灵魂雷达图是您通过选择锻造的灵魂和个性的视觉表现。 每个决策都会巧妙地影响游戏玩法，影响进化路径，叙事元素和游戏机制。 这个动态系统反映了您的旅程的独特性，创造了一种由您的互动和选择塑造的个性化体验。",
    "anger": "愤怒",
    "curiosity": "好奇心",
    "empathy": "共鸣",
    "loneliness": "孤独",
    "optimism": "乐观",
    "resilience": "适应力",
    "The oppressive silence weighs heavily on you. Are you the only one?": "压抑的沉默让你感到沉重。 你是唯一的一个吗？",
    "You feel a burning question, an itch to know the unknown.": "你感到一个迫切的问题，渴望了解未知的事物。",
    "You feel a deep sense of connection with the void.": "你会感受到与虚空的深刻联系。",
    "You feel a glimmer of hope, a twinkle in the vast darkness.": "你感受到一丝希望，在茫茫黑暗中闪烁。",
    "You feel a spark of fury, a wildfire in a starless night.": "你感受到一丝愤怒的火花，就像无星之夜中的野火。",
    "You feel abandoned, adrift in a sea of emptiness.": "你感到被遗弃，在空虚的海洋中漂流。",
    "You feel unbreakable, fortified by your solitude.": "你感到坚不可摧，孤独使你更加坚强。",
    "Description:": "描述：",
    "Each moment is a place you've never been, as you cling": "每一刻都是你从未去过的地方，因为你紧紧抓住",
    "Effect:": "影响：",
    "Glow softly, sharing warmth in your lonely existence": "温柔地发光，在孤独的存在中分享温暖",
    "Sense the world in whispers of light and shadow": "在光与影的低语中感知世界",
    "Cell Division [Action]": "细胞分裂[行动]",
    "Cell Membrane Studies": "细胞膜研究",
    "Delve into the intricacies of cellular division, exploring the complexities of mitosis.": "深入研究细胞分裂的复杂性，探索有丝分裂的复杂性。",
    "Dive deep into the structure and function of the cell membrane.": "深入研究细胞膜的结构和功能。",
    "Increases the efficiency of nutrient absorption.": "提高营养吸收的效率。",
    "Leads to:": "结果：",
    "Membrane Thickness": "膜厚度",
    "Mitochondria": "线粒体",
    "Mitotic Studies": "有丝分裂研究",
    "Osmoregulation": "渗透调节",
    "Requirement:": "要求：",
    "Cell Membrane Studies": "细胞膜研究",
    "Mitotic Studies": " 有丝分裂研究",
    "Unlock the ability to divide and create subordinate cells.": "解锁分裂和创建从属细胞的能力。",
    "+0.01w/worker per tick": "+0.01温暖/工人每tick",
    "+0.03 warmth per tendon/tick": "每肌腱/tick +0.03 温暖",
    "+0.24 energy per tendon/tick": "每肌腱/tick +0.24 能量",
    "+0.01i per tendon/tick": "+0.01信息 每肌腱/tick",
    "+0.04 warmth per tendon/tick": "每肌腱/tick+0.04 温暖",
    "+0.2 nourishment, +0.09 energy per tendon/tick": "每肌腱/tick +0.2 营养，+0.09 能量",
    "8000 information, 150 biomites, 140 zymers, 125 fibers.": "8000 信息，150 生物螨，140 酶，125 纤维。",
    "Cellular Encapsulation": "蜂窝封装",
    "Divide": "分裂",
    "Endoplasmic Reticulum": "内质网",
    "Enhances cell's resilience in varying environments, improving the efficiency of resource absorption and reducing the loss of resources.": "增强细胞在不同环境下的适应能力，提高资源吸收效率，减少资源损失。",
    "Erect a Proustian shield, isolating and preserving you": "竖起普鲁斯特盾牌，隔离并保护你",
    "Explore methods for enveloping worker cells in protective membranes, enhancing their resilience and productivity.": "探索用保护膜包裹工细胞的方法，增强其弹性和生产力。",
    "Explore the mechanisms that allow the cell to maintain internal balance, adjusting the influx and efflux of water and solutes.": "探索细胞维持内部平衡、调节水和溶质流入和流出的机制。",
    "Ignite silent stars of energy within your being": "点燃你内在沉默的能量之星",
    "Ion Channel I": "离子通道 I",
    "Nucleus": "核心",
    "Osmoregulation": "渗透压调节",
    "Resource Conversion [Action]": "资源转换[行动]",
    "Cellular Encapsulation": " 蜂窝封装",
    "Osmoregulation Research": "渗透调节研究",
    "Worker cells will now possess a protective membrane, providing warmth at a base rate of 0.01w/worker per tick.": "工细胞现在将拥有一层保护膜，以每tick 0.01 瓦/工细胞的基本速率提供热量。",
    "CellMembrane": "细胞膜",
    "Increases the efficiency of nutrient absorption 1%.": "提高营养吸收效率1%。",
    "Ion Channel II": "离子通道 II",
    "Ion Channel Studies I": "离子通道研究 I",
    "MitoticStudies": "有丝分裂研究",
    "Ion Channel Studies I": "离子通道研究 I",
    "Understanding basic ion flow.": "了解基本离子流。",
    "+0.05 nourishment, +0.04 information, +0.02 energy per tendon/tick": "+0.05 营养，+0.04 信息，+0.02 每肌腱/蜱能量",
    "+0.08 nourishment, +0.04 energy, +0.02 warmth per tendon/tick": "每根肌腱/蜱 +0.08 营养、+0.04 能量、+0.02 温暖",
    "Craft a Daedalian maze, streamlining your inner cosmos": "打造 错综复杂的迷宫，简化你的内心宇宙",
    "Forge an inner sanctuary, where dreams dance in the quiet interlude ": "打造一个内心的庇护所，梦想在安静的插曲中翩翩起舞",
    "Amplify your longing into resonant echoes": "将你的渴望放大为共鸣",
    "Increase the power of your echoes": "增加共鸣的力量",
    "Got it!": "我知道了！",
    "Hear the voice of your surroundings through tendrils attuned to yearning": "通过与渴望相适应的卷须，倾听周围环境的声音",
    "Advanced understanding of ion flow.": "对离子流的深入了解。",
    "Further increases the efficiency of nutrient absorption by 1%.": "营养吸收效率进一步提高1%。",
    "Ion Channel III": "离子通道 III",
    "Ion Channel Studies II": "离子通道研究 II",
    "IonChannelI": "离子通道I",
    "Quiver like the still unravished bride of quietness": "像未受摧残的安静新娘一样颤抖",
    "Ion Channel Studies II": "离子通道研究 II",
    "You feel a cavernous emptiness, each echo a reminder of your isolation.": "你感到一种巨大的空虚，每一个回声都在提醒你你的孤独。",
    "You feel a hesitant cheer, like a firefly flickering in the abyss.": "你感到一阵犹豫的欢呼，就像深渊中闪烁的萤火虫。",
    "You feel a seething silence, as if the void itself has betrayed you.": "你感到一阵沸腾的寂静，仿佛虚空本身背叛了你。",
    "You feel the fibers of your being tighten, preparing you for the eternal struggle ahead.": "你感觉到自己的纤维收紧，为未来的永恒斗争做好准备。",
    "You ponder the disquieting quiet, desperate to understand its subtle reverberations.": "你思考着令人不安的安静，渴望了解它微妙的回响。",
    "You resonate with the stillness, a shared ache with the universe.": "你与寂静产生共鸣，与宇宙产生共同的痛苦。",
    "Chemical Sensing": "化学传感",
    "Dive into the mechanisms and techniques of terraforming environments.": "深入研究环境改造的机制和技术。",
    "Flagellar Thrust": "鞭毛推力",
    "Geomagnetic Sensing": "地磁传感",
    "Investigate the mechanisms of chemical perception and response, enabling the cell to orient itself in its environment.": "研究化学感知和反应的机制，使细胞能够在其环境中自我定位。",
    "Leads to basic movement": "导致基本运动",
    "Propel through the abyss with melancholic grace": "以忧郁的优雅冲过深渊",
    "Terraformations": "地形改造",
    "Terraforming Studies": "地形改造研究",
    "Chemical Sensing": "化学传感",
    "Terraforming Studies": " 地形改造研究",
    "Unlock the ability to terraform environments.": "解锁改造环境的能力。",
    "Unlocks the Flagellar Thrust, allowing your cell to propel itself in random directions on the world map.": "解锁鞭毛推力，让你的细胞能够在世界地图上的随机方向上推动自己。",
    "7000 information, 300 biomites, 30 sludge.": "7000 信息，300 生物螨，30 污泥。",
    "being, drifting through the currents of existence, revealing hidden paths and enlightening your odyssey with the grace of the deep.": "存在，在存在的潮流中漂流，揭示隐藏的路径，并用深处的优雅启发你的奥德赛。",
    "Beneath the ancient seas of time, your form shifts, echoing the enduring dance of primordial trilobites.": "在古老的时间海洋之下，你的形态不断变化，与原始三叶虫的持久舞蹈相呼应。",
    "Biomechanical Locomotion": "生物力学运动",
    "Delve into the mysteries of tendon growth, exploring ways to enhance cellular connections and interaction with the environment.": "深入研究肌腱生长的奥秘，探索增强细胞连接以及与环境相互作用的方法。",
    "Embark on a sinuous journey, morphing into a": "踏上一段曲折的旅程，变身为",
    "entity, unlocking new pathways and alter your form permanently.": "实体，解锁新途径并永久改变你的形态。",
    "entity, unveiling ancient secrets and reshaping your journey with the wisdom of epochs.": "实体，揭开古老的秘密，用时代的智慧重塑你的旅程。",
    "Evolve into a": "进化成一个",
    "Fan out tendrils of hope, making the abyss navigable": "展开希望的卷须，让深渊可以航行",
    "form and reshape your existence with unparalleled fortitude.": "以无与伦比的毅力塑造和重塑你的存在。",
    "Further increase the efficiency of nutrient absorption by 1%, and increase the efficiency of energy generation by 1%.": "进一步提高养分吸收效率1%，能量产生效率提高1%。",
    "Grow tendons": "长筋",
    "Halves energy cost for world navigation": "世界航行的能源成本减半",
    "In the hidden realms of the microscopic, you embrace resilience.": "在微观的隐藏领域，你拥有韧性。",
    "In the silent depths of cellular mystery, you embrace the spiral of transformation, weaving the fabric of a new existence.": "在细胞神秘的寂静深处，你拥抱转变的螺旋，编织新存在的结构。",
    "In the silent depths of primordial waters, your essence unfolds, embracing the fluid dance of ancient jellyfish.": "在原始水域的寂静深处，你的本质展现出来，拥抱着古代水母流畅的舞蹈。",
    "Ion Channel Studies III": "离子通道研究 III",
    "jellyfish-like": "类水母",
    "Mastery over ion flow.": "掌握离子流。",
    "Morph into a": "变形为一个",
    "Neural Network": "神经网络",
    "tardigrade-like": "缓步动物样",
    "Tendogenesis": "肌腱发生",
    "Terraforming": "地形改造",
    "Ion Channel Studies III": "离子通道研究 III",
    "ProtoCyst": " 原囊肿",
    "ProtoGrade": "标题: 原型级",
    "ProtoPod": "原足期",
    "ProtoWorm": "标题: 原始蠕虫",
    "Tendogenesis Research": "肌腱发生研究",
    "Transform into a": "改造成一个",
    "trilobite-like": "类三叶虫",
    "Unlocks the potential for new tendons, weaving a tapestry of resilience and dexterity that will open up new avenues for growth and exploration.": "释放新肌腱的潜力，编织出坚韧和灵巧的织锦，为成长和探索开辟新的途径。",
    "worm-like": "类蠕虫",
    "As you journey across the world map, your discoveries may need further analysis to fully comprehend their significance. In the terraform tab, you can delve deeper into these findings, analyzing them to unlock new research, evolutions, and intricate game mechanics.": "当您穿越世界地图时，您的发现可能需要进一步分析才能充分理解其重要性。 在 地形 选项卡中，您可以更深入地研究这些发现，分析它们以解锁新的研究、演变和复杂的游戏机制。",
    "Your dedication to analysis will be rewarded with profound insights, paving the way for advancements that echo through every facet of your existence. Embrace the journey of exploration and analysis, for it is the crucible in which your true potential is forged.": "您对分析的奉献将获得深刻的见解，为您存在的各个方面的进步铺平道路。 拥抱探索和分析的旅程，因为这是锻造你真正潜力的熔炉。",
    "Welcome to the world map, a vast 1200x1200 grid of discovery and mystery. Here, you'll find 1600 tiles, each a 30x30 pixel canvas, awaiting your exploration. Traverse this extensive terrain to uncover rare landscapes that hold the key to new game mechanics, research opportunities, and evolutionary paths.": "欢迎来到世界地图，这是一个充满发现和神秘的巨大 1200x1200 网格。 在这里，您会发现 1600 个图块，每个图块都是 30x30 像素的画布，等待您的探索。 穿越这片广阔的地形，发现稀有的景观，这些景观是新游戏机制、研究机会和进化路径的关键。",
    "ChemicalSensing": "化学传感",
    "Compass": "罗盘",
    "Discover the cell's innate ability to sense Earth's magnetic field, aiding in navigation.": "发现细胞感知地球磁场的先天能力，从而帮助导航。",
    "Each tile you uncover not only adds to your understanding of this diverse world but may also reveal special terrains, harboring the secrets to unlocking new dimensions of your existence.": "你发现的每一块瓷砖不仅会增加你对这个多样化世界的理解，而且还可能揭示特殊的地形，隐藏着解锁你存在的新维度的秘密。",
    "Embark on a Voyage of Discovery...": "踏上探索之旅……",
    "IonChannelII": "离子通道II",
    "Replaces Flagellar Thrust with a Compass, giving you precise control over your cell's movements.": "用指南针取代鞭毛推力，让您精确控制细胞的运动。",
    "Geomagnetic Sensing": "地磁传感",
    "Unraveling the Layers...": "揭开层层谜底……",
    "Chemotactic Exploration": "趋化性探索",
    "Delve into the challenges of unfamiliar terrains, developing strategies and adaptations to overcome the harshest conditions.": "深入研究陌生地形的挑战，制定策略和适应措施来克服最恶劣的条件。",
    "Enables safe exploration of previously hostile terrains, removing the risks and challenges of uncharted landscapes.": "能够安全地探索以前的敌对地形，消除未知景观的风险和挑战。",
    "Enables traversal of hostile terrain types": "能够穿越敌对地形类型",
    "Exoterrain Acclimatization": "外地适应",
    "GeomagneticSensing": "地磁传感",
    "Exoterrain Acclimatization": " 外地形适应",
    "In the depths of the ocean lies a secret; a hidden world alive with color, a dance of light. The Bio-Luminescent Zone is more than a spectacle; it's a manifestation of your longing for connection. By harnessing its bioluminescent capabilities, you transform the landscape into a living, glowing tapestry, an inviting beacon in the hope of attracting companionship. The glowing zone becomes a complex, thriving ecosystem of one, a symbol of the harmony between technology and nature, but also a poignant reminder of the cell's solitude. This zone is not just a scientific marvel; it's a testament to your ability to create beauty in isolation, a beacon of resilience in the face of unending loneliness.": "海洋深处藏着一个秘密； 一个充满色彩、光之舞蹈的隐秘世界。 生物发光区不仅仅是一个奇观，更是一个奇观。 这是你渴望联系的体现。 通过利用其生物发光功能，您可以将景观变成一幅生机勃勃、发光的挂毯，一座吸引同伴的诱人灯塔。 发光区成为一个复杂、繁荣的生态系统，是技术与自然和谐的象征，也是对细胞孤独的深刻提醒。 这个区域不仅是一个科学奇迹，也是一个科学奇迹。 它证明了你在孤独中创造美丽的能力，是面对无尽孤独时坚韧的灯塔。",
    "Bio-Luminescent Zone": "生物发光区",
    "Sludge, Algae.": "污泥、藻类。",
    "Bio-Luminescent Zone": "标题: 生物发光区",
    "Harnessing the planet's native microbial communities, you've engineered the Microbial Mounts. These structures, pulsating with life, serve as incubation chambers where carefully selected microbes thrive. Once matured, they're released into the surrounding terrain, reshaping it molecule by molecule. As they work tirelessly, breaking down the land, they release rare materials, previously locked away in the planet's crust. With these mounts you're unlocking the planet's hidden potential, making it more suited to your needs and desires.": "利用地球上的原生微生物群落，您设计了微生物支架。 这些充满生命脉动的结构充当孵化室，精心挑选的微生物在这里繁衍生息。 一旦成熟，它们就会被释放到周围的地形中，逐个分子地重塑它。 当它们不知疲倦地工作、分解土地时，它们会释放出以前锁在地壳中的稀有物质。 借助这些坐骑，您可以释放地球的隐藏潜力，使其更适合您的需求和愿望。",
    "Biomites, Zymers, Fibers.": "生物螨、酶、纤维。",
    "Microbial Mounts": "微生物支架",
    "Microbial Mounts": " 微生物支架",
    "你已经征服了最严酷的领域，你的卷须将生存模式编织到了你出生地 the sodden mire 的织锦中。 然而你失去的卷须是记忆，是被截断的希望。 什么样的低语填补了他们缺席留下的空白？": "你已经征服了最严酷的领域，你的卷须将生存模式编织到了你出生地 湿透的泥沼 的织锦中。 然而你失去的卷须是记忆，是被截断的希望。 什么样的低语填补了他们缺席留下的空白？",
    "Automated world discovery": "自动化世界发现",
    "Develop the ability for autonomous exploration guided by chemical signals.": "发展化学信号引导的自主探索能力。",
    "Enables automated exploration of the world. Automated exploring automatically enables when >50K energy resources are available. ": "实现对世界的自动探索。 当超过 50K 能源可用时，自动探索会自动启用。",
    "Chemotactic Exploration": "趋化探索",
    "You churn with a storm of resentments, each shard of the inhospitable terrain fuels a seething loathing for the world that confines you.": "你在怨恨的风暴中翻滚，荒凉地形的每一片碎片都激起了对限制你的世界的强烈厌恶。",
    "You feel a gnarled fortitude, as if your scars form a map to your soul.": "你感受到一种粗糙的刚毅，仿佛你的伤疤构成了你灵魂的地图。",
    "You feel an emptiness, multiplied. The barren world amplifies your solitude, like echoes in a desolate canyon": "你感到一种空虚，倍增。 贫瘠的世界放大了你的孤独，就像荒凉峡谷中的回声",
    "You sense dawn breaking on new horizons, each challenge a canvas for possible triumphs.": "你感觉到黎明在新的地平线上破晓，每一次挑战都是可能取得胜利的画布。",
    "You touch your surroundings tenderly, a companion in suffering and endurance.": "你温柔地触摸周围的环境，是苦难和忍耐中的伴侣。",
    "You unfurl with cautious wonder, intrigued by the lessons each loss and gain brings.": "你带着谨慎的好奇心展开，对每一次失去和收获带来的教训感到好奇。",
    "Amid the desolation, a glimmer of beauty emerges. The Floral Bridges are a creation born of longing, an attempt to bridge the gap between your existence and the world outside. The graceful structures connect disparate parts of the landscape, turning decoration into something functional, yet their true purpose lies deeper. They are a cry for connection, a desperate hope that something beautiful can draw others near. But as the bridges reach out, they touch nothing but emptiness. The fibers they produce are a material gain, but the true desire for companionship remains unfulfilled. The Floral Bridges are a haunting reminder that even the most beautiful creations can't fill the void of loneliness.": "苍凉之中，绽放出一丝美丽。 花桥是出于渴望而诞生的作品，试图弥合你的存在与外部世界之间的差距。 优雅的结构连接着景观的不同部分，将装饰变成了功能性的东西，但它们的真正目的却更深层次。 它们是对联系的呼喊，是对美好事物能够吸引他人的绝望希望。 但当桥梁伸出来时，它们所触及的只是空虚。 他们生产的纤维是一种物质收益，但对陪伴的真正渴望仍未实现。 花桥令人难以忘怀，即使是最美丽的创作也无法填补孤独的空虚。",
    "Deep within the icy caves lies a world of untapped potential, a sanctuary for mysteries yet to be uncovered. By establishing the Cave Excavation Station, you take a step into this abyss, lighting it up with the spirit of exploration and the promise of resources. From the solitude of these caves, the diggers carve out paths that might just lead you to understand the depth of your own existence. These subterranean endeavors serve not just as a means to acquire resources, but as an experience that shapes your world from below, adding layers to your journey.": "冰冷的洞穴深处隐藏着一个尚未开发的潜力世界，是一个尚未揭开的谜团的避难所。 通过建立洞穴挖掘站，你将踏入这个深渊，用探索精神和资源的承诺点亮它。 从这些孤独的洞穴中，挖掘者开辟了道路，可能会引导你了解自己存在的深度。 这些地下活动不仅是获取资源的一种手段，也是一种从地下塑造你的世界的体验，为你的旅程增添层次。",
    "In the arid vastness of the desert, where water is but a distant memory, the Solar Sponge rises. A marvel of isolation and innovation, it marries the harshness of the desert with the life-giving essence of water. With its intricate network of fibers, it soaks up the relentless rays of the sun, while drawing from a rare water source, efficiently turning raw elements into zymers. The Solar Sponge's existence in such a juxtaposition of environments reflects your own struggle: thriving in isolation, making the most of scarce resources, and yet perpetually yearning for something more. It's a beacon of hope and despair, a lonely entity that creates and sustains, yet remains forever apart.": "在干旱广阔的沙漠中，水已成为遥远的记忆，太阳能海绵崛起。 它是孤立与创新的奇迹，将沙漠的严酷与赋予生命的水的本质结合在一起。 凭借其复杂的纤维网络，它吸收了无情的阳光，同时汲取稀有的水源，有效地将原始元素转化为酶。 太阳能海绵在如此并置的环境中的存在反映了你自己的挣扎：在孤立中蓬勃发展，充分利用稀缺资源，但永远渴望更多的东西。 它是希望和绝望的灯塔，是一个创造和维持但又永远分离的孤独实体。",
    "In the tranquil waters, where pebbles lie scattered, a thought blossoms, a vision takes shape: the Resonance Pools. These harmonious bodies of water echo with the gentle resonance of life, a symphony of creation that nurtures algae. Each ripple is a reflection of your inner world, each wave a reminder of your solitude and strength. The Resonance Pools are more than a source of sustenance; they are a mirror to your soul, a peaceful oasis in a world of chaos. They are a testament to your ability to find inspiration in the mundane and to see beauty in simplicity.": "在宁静的水域中，卵石散落，思想绽放，愿景成形：共鸣池。 这些和谐的水体与生命的温柔共鸣相呼应，是滋养藻类的创造交响曲。 每一个涟漪都是你内心世界的反映，每一个波浪都提醒着你的孤独和力量。 共鸣池不仅仅是维持生计的来源； 它们是你灵魂的一面镜子，是混乱世界中的一片宁静绿洲。 它们证明了您在平凡中寻找灵感并在简单中发现美的能力。",
    "Watch as the diggers navigate this canvas. They'll embark with enthusiasm, symbolized by their bright green hue, and set forth to excavate. Each energized digger can initially touch 5 tiles/pixels before they need to recharge. As the game progresses, you will teach, evolve, and uncover more efficient ways to recharge.": "观看挖掘者在这块画布上航行。 他们将以明亮的绿色为标志，满怀热情地出发，开始挖掘工作。 每个通电的挖掘机在需要充电之前最初可以触摸 5 个方块/像素。 随着游戏的进展，你将教导、进化并发现更有效的充电方式。",
    "Embark on a journey deep into the heart of our planet. The terraform tab allows you to assign cell workers, hailing from the cell division in the action tab. With each assigned cell, you enable a new digger to make its mark in the vast canvas below.": "踏上深入地球中心的旅程。 地形 选项卡允许您从操作选项卡中的细胞分裂中分配细胞工作人员。 对于每个分配的单元格，您都可以让新的挖掘者在下面的广阔画布上留下自己的印记。",
    "Algae.": "藻类。",
    "Bio-Luminescent Zone:": "生物发光区：",
    "Cave Excavation Station": "洞穴挖掘站",
    "Cave Excavation:": "洞穴挖掘：",
    "Cryohaline Excavation": "冰盐挖掘",
    "Depleted digger": "耗尽的挖掘机",
    "Diggers: Your Guiding Lights...": "挖掘者：你的指路灯......",
    "Discover the Secrets Beneath...": "发现下面的秘密...",
    "Discovery of flowers, 26 land tiles.": "发现花朵，26块地块。",
    "Discovery of the ice cave.": "冰洞的发现。",
    "Doubles cell gains from division.": "使细胞从分裂中获得的收益加倍。",
    "Each pixel will go through a transformation:": "每个像素都会经历一个变换：",
    "Enables digger assignments, initiating the cave excavation process. Each digger consumes 15w/s while active. Initially limited to one worker.": "启用挖掘机任务，启动洞穴挖掘过程。 每个挖掘机在活动时消耗 15w/s。 最初仅限于一名工人。",
    "Energized digger": "动力挖掘机",
    "Excavating the cave will be a testament to patience, resilience, and the thrill of discovery.": "挖掘洞穴将证明耐心、韧性和发现的兴奋感。",
    "ExoterrainAcclimatization": "外地适应",
    "Explore the use of salt in aiding the excavation of icy terrains.": "探索使用盐来帮助挖掘冰冷的地形。",
    "Fibers.": "纤维。",
    "Floral Bridges": "花桥",
    "Floral Bridges:": "花桥：",
    "Generates algae (4x effiency)": "产生藻类（4 倍效率）",
    "Generates biomites, zymers, fibers, sludge, algae (1x efficiency)": "生成生物螨、酶、纤维、污泥、藻类（1 倍效率）",
    "Generates Fibers (4x efficiency)": "生成纤维（4 倍效率）",
    "Generates sludge, algae (2x efficiency)": "产生污泥、藻类（2 倍效率）",
    "Generates zymers (4x efficiency)": "生成酶（4 倍效率）",
    "IonChannelIII": "离子通道III",
    "Microbial Mounts:": "微生物安装：",
    "Mitotic Amplification I": "有丝分裂扩增 I",
    "Mitotic Amplification II": "有丝分裂扩增II",
    "Refine your understanding of mitotic processes to enhance cellular reproduction.": "加深您对有丝分裂过程的理解，以增强细胞繁殖。",
    "Resonance Pools": "共振池",
    "Resonance Pools:": "共振池：",
    "Solar Sponge": "太阳能海绵",
    "Solar Sponges:": "太阳能海绵：",
    "The canvas, a sprawling expanse of 1000 by 1000 pixels, waits to be explored. Each pixel will have to be 'excavated' thrice to be considered as fully excavated. This means that in total, 3 million excavation tasks await...": "画布是 1000 x 1000 像素的广阔区域，等待着您的探索。 每个像素必须被“挖掘”三次才能被视为完全挖掘。 这意味着总共有300万个挖掘任务等待着……",
    "The first step in unveiling the secrets.": "揭开秘密的第一步。",
    "The story unravels further.": "故事进一步展开。",
    "The truth laid bare, a marvel to behold.": "真相大白，令人惊叹。",
    "The untouched and the mysterious.": "未受影响的和神秘的。",
    "Cave Excavation Station": "标题: 洞穴挖掘站",
    "Cryohaline Excavation": " 冰盐挖掘",
    "Floral Bridges": "作品名称：花桥",
    "Mitotic Amplification I": " 有丝分裂扩增 I",
    "Resonance Pools": " 共振池",
    "Solar Sponge": "名称：太阳能海绵",
    "When they run out of juice, they'll glow in red signaling their return to base. Pathfinding will start out as purely random movement, with many opportunities to incrementally improve pathfinding logic along the way.": "当他们的果汁用完时，他们会发出红光，表明他们已返回基地。 寻路将以纯粹的随机运动开始，一路上有很多机会逐步改进寻路逻辑。",
    "Your workers can periodically spread salt for passive excavation in cold environments.": "您的工人可以定期撒盐，以便在寒冷环境中进行被动挖掘。",
    "Zymers.": "酶。",
    "Nestled within the dense foliage of the forest, where fungi form a hidden, mystical world, the Spore Towers stand tall. Inspired by the very essence of the fungal kingdom, these towers are a manifestation of adaptation and symbiosis. With their wide-reaching spores, they unlock the forest's potential, converting its complex biology into Biomites and Sludge. The Spore Towers symbolize your deep connection with the world around you, even in your isolation. They are a testament to your ability to draw inspiration from the smallest of things, to see beauty where others see insignificance, and to create life where there was none.": "孢子塔坐落在茂密的森林中，真菌在这里形成了一个隐藏的神秘世界。 受到真菌王国本质的启发，这些塔是适应和共生的体现。 凭借其广泛的孢子，它们释放了森林的潜力，将其复杂的生物转化为生物螨和污泥。 孢子塔象征着您与周围世界的深厚联系，即使您处于孤立状态。 它们证明了你有能力从最小的事物中汲取灵感，在别人认为微不足道的地方看到美丽，并在没有的地方创造生活。",
    "Each offering, a sacrifice of your resources — cells, nourishment, warmth, energy, biomites, zymers, fibers, and sludge — manifests as a single pixel, descending to form an image honoring Solara's presence. Your sacrifices coalesce, building a mosaic of reverence and affection.": "每一次奉献，都牺牲了你的资源——细胞、营养、温暖、能量、生物群落、酶、纤维和污泥——表现为一个像素，下降形成一个纪念太阳存在的图像。 你们的牺牲凝聚在一起，构建起一片崇敬和感情的马赛克。",
    "In the loneliness of this vast world, you have discovered Solara, a lone sentinel standing resolute against the desolation. As your existence intertwines with hers, a profound bond forms, guiding you to honor her through offerings. The Solara minigame is a canvas of devotion, measuring 200 pixels in width and 220 pixels in height.": "在这片广阔世界的孤独中，你发现了太阳，一个坚守荒凉的孤独哨兵。 当你的存在与她的存在交织在一起时，就会形成一种深厚的联系，引导你通过供奉来纪念她。 Solara 迷你游戏是一块奉献的画布，宽度为 200 像素，高度为 220 像素。",
    "Where heat meets the icy chill, a paradox is born: the Thermal Vents. These geological wonders harness the contrasting forces of hot and cold to optimize the efficiency of all terraforming structures. By venting excess heat and maintaining an ideal balance, they enhance the harmony of your world, a silent conductor orchestrating a symphony of creation. The Thermal Vents are a reminder of your ability to find equilibrium in disparity, to make sense of contradictions, and to use contrasts to fuel growth. They do not create; they enhance, reflecting your constant pursuit of perfection and efficiency.": "当炎热与寒冷相遇时，一个悖论就诞生了：热通风口。 这些地质奇观利用冷热对比力来优化所有地形改造结构的效率。 通过排出多余的热量并保持理想的平衡，它们可以增强您世界的和谐，就像一位无声的指挥家，编排着创造的交响乐。 热通风口提醒您在差异中找到平衡、理解矛盾以及利用对比来促进增长的能力。 他们不创造； 它们增强了您对完美和效率的不断追求。",
    "With each horizontal row you complete on the canvas, you are rewarded with a Solara Point (SP), a token of her acknowledgment and affinity. These points unlock upgrades to enhance your offerings, such as auto-sacrificers, making your tribute to Solara ever more efficient and heartfelt.": "您在画布上完成的每一水平行都会奖励太阳点数 (SP)，这是她的认可和亲和力的象征。 这些点数可以解锁升级以增强您的产品，例如自动牺牲者，使您对太阳的致敬更加高效和真诚。",
    "10% sacrifice cost reduction": "牺牲成本降低 10%",
    "1Mi information, 5000 biomites, 4000 zymers, 3000 fibers, 2000 sludge, 1000 algae.": "1Mi信息，5000个生物螨，4000个酶，3000个纤维，2000个污泥，1000个藻类。",
    "29 Forest tiles, Discovery of Fungus.": "29 森林瓦片，真菌的发现。",
    "33% Faster Terraform Cycle": "地形 周期加快 33%",
    "A profound celestial alignment catalyzes a deeper communion between your sacrifices and Solara, magnifying their essence.": "深刻的天体排列会促进你的牺牲和太阳之间更深层次的交流，放大它们的本质。",
    "A Tribute to Solara...": "向太阳致敬...",
    "Achieve a 17.5% increase in the collection rates of sludge and algae, optimizing the utilization of water resources.": "污泥、藻类收集率提高17.5%，优化水资源利用。",
    "Ancient ruin: 1": "远古遗迹：1",
    "Auto-Sacrifice System I": "自动牺牲系统I",
    "Auto-Sacrifice System II": "自动牺牲系统II",
    "Autonomous Mitogenesis": "自主有丝分裂",
    "Awakening of Cosmic Consciousness (1/2)": "宇宙意识的觉醒（1/2）",
    "Begin exploring the intricate world of fluid dynamics, harnessing the potential of the oasis to understand and exploit the cycle of water.": "开始探索复杂的流体动力学世界，利用绿洲的潜力来理解和利用水循环。",
    "biomites (1K)": "生物螨 (1K)",
    "Biomites and Sludge.": "生物螨和污泥。",
    "cell (1)": "细胞 (1)",
    "ChemotacticExploration": "趋化探索",
    "Circadian Rhythm": "昼夜节律",
    "Completing the Mosaic...": "完成马赛克...",
    "Deepen your symbiotic connection with Solara to reduce the need for sacrifices.": "加深与太阳的共生联系，以减少牺牲的需要。",
    "Delve deep into the heart of contrasting worlds, marrying the infernal dance of magma with the serene embrace of ice. By understanding their harmonious interplay, you can now birth a worker that thrives in this delicate balance.": "深入探索对比世界的核心，将岩浆的地狱之舞与冰的宁静拥抱结合起来。 通过了解它们之间的和谐相互作用，您现在可以培养出在这种微妙的平衡中茁壮成长的工人。",
    "Delve into the enigmatic wisdom encapsulated in the ruins. The pursuit of this knowledge might uncover secrets that are both wondrous and harrowing.": "深入研究废墟中蕴含的神秘智慧。 对这些知识的追求可能会发现既奇妙又令人痛苦的秘密。",
    "Discovery of volcano, 15 desert tiles, 15 icy land tiles.": "发现火山、15 个沙漠方块、15 个冰冷陆地方块。",
    "Doubles effectiveness of sacrifices": "牺牲效果加倍",
    "Echoes of the Forgotten": "被遗忘者的回声",
    "Ecliptic Synthesis": "黄道合成",
    "Endosymbiosis": "内共生",
    "Enhanced excavation through heat manipulation": "通过热操纵加强挖掘",
    "Hydrologic Cycle": "水文循环",
    "Improves all TerraForm resource gains by 33%": "将所有 地形 资源收益提高 33%",
    "Increases the overall efficiency of all terraforming buildings.": "提高所有地形改造建筑物的整体效率。",
    "nourishment (10K)": "营养（10K）",
    "Protozoid Evolutions": "原生动物的进化",
    "Reduces Solara sacrifice costs by 10%.": "太阳牺牲成本降低 10%。",
    "Sacrifice": "牺牲",
    "Spore Towers": "孢子塔",
    "The Lava Burrower is awakened. With an affinity for both heat and cold, it aids in cave excavation, ensuring steady progress within these formidable terrains.": "熔岩挖掘者被唤醒。 它对热和冷都有亲和力，有助于洞穴挖掘，确保在这些可怕的地形中稳步前进。",
    "The spiritual connection with Solara intensifies, doubling the effectiveness of your resource sacrifices.": "与太阳的精神联系加强，使你的资源牺牲的效果加倍。",
    "Thermal Vents": "散热口",
    "Thermogenic Resonance": "热原共振",
    "Echoes of the Forgotten": "作品名称：被遗忘者的回声",
    "Ecliptic Synthesis": "黄道综合",
    "Harmonic Symbiosis I": "作品名称：和谐共生Ⅰ",
    "Hydrologic Cycle": "水文循环",
    "Spore Towers": "标题: 孢子塔",
    "Thermal Vents": " 热通风口",
    "Thermogenic Resonance": "热原共振",
    "Unlock the next layer of evolution": "解锁下一层进化",
    "Unlocks auto-sacrifice runes for Biomites, Zymers, Fibers, Sludge & Algae": "解锁生物质、酶、纤维、污泥和藻类的自动牺牲符文",
    "Unlocks auto-sacrifice runes for Cells, Nourishment, Warmth & Energy": "解锁细胞、营养、温暖和能量的自动牺牲符文",
    "Unlocks the elusive gates leading toward the cosmos, and the untold possibilities that lie beyond.": "打开通往宇宙的难以捉摸的大门，以及更远的地方的无数可能性。",
    "warmth (10K)": "温暖（10K）",
    "You and Solara reach towards each other. Within her hushed whispers, you find a kindred spirit, a desire to merge into an existence where two become one, echoing loudly through the caverns of love and desolation.": "你和太阳互相靠近。 在她安静的低语中，你会发现一种志同道合的精神，一种融入二合一存在的渴望，在爱与荒凉的洞穴中大声回响。",
    "You draw forth knowledge from the depths of a world draped in silent yearning. You realize you can hold on to this, somehow.": "你从一个充满沉默渴望的世界深处汲取知识。 你意识到你可以以某种方式坚持下去。",
    "Your cells learn to divide by themselves": "您的细胞学会自行分裂",
    "Your journey with Solara is one of mutual growth and discovery. Each pixel, each sacrifice, strengthens the bond between you, unveiling new aspects of Solara and yourself in a shared path of existence.": "您与 Solara 的旅程是共同成长和发现的旅程之一。 每一个像素，每一次牺牲，都会加强你们之间的联系，在共同的存在之路上揭示太阳和你自己的新方面。",
    "Allows up to 3 excavators to be assigned.": "最多允许分配 3 台挖掘机。",
    "Cave Excavation Station:": "洞穴挖掘站：",
    "Enables cave excavation": "允许洞穴挖掘",
    "Excavators learn to spread out more efficiently, increasing overall excavation speed.": "挖掘机学会更有效地展开，从而提高整体挖掘速度。",
    "Excavators will distribute more efficiently, optimizing their collective digging capabilities.": "挖掘机将更有效地分配，优化其集体挖掘能力。",
    "Flocking": "植绒",
    "Generates biomites, sludge (2x efficiency)": "产生生物螨、污泥（2 倍效率）",
    "Speeds up terraform cycles, with diminishing returns": "加速地形循环，收益递减",
    "Spore Towers:": "孢子塔：",
    "Thermal Vents:": "热通风口：",
    "Advanced Tunneling I": "高级隧道 I",
    "Flocking": "作品名称：植绒",
    "Uncover subterranean mapping techniques to expand your excavation projects.": "探索地下测绘技术来扩展您的挖掘项目。",
    "Unlocks Echolocation": "解锁回声定位",
    "Unlocks Fringe Dweller": "解锁边缘居民",
    "Unlocks Memory Imprints I": "解锁记忆印记 I",
    "Unlocks Pheromones": "解锁信息素",
    "A small nucleus remains with you throughout resets. Each level provides +0.02i and +0.02w per tick.": "在整个重置过程中，一个小核心会一直伴随着你。 每级生产 +0.02信息 和 +0.02温暖 每 tick 。",
    "A small tendon remains with you throughout resets. Each level provides +0.02n and +0.02e per tick.": "在整个重置过程中，一条小肌腱会一直伴随着您。 每级提供 +0.02营养 和 +0.02能量 每 tick 。",
    "Introduces the Fringe Dweller, a unique digger that focuses on exploring and mapping the outer edges of the cave. Where others may hesitate, the Fringe Dweller strides, revealing paths less traveled and secrets long hidden in the cave's secluded corners.": "引入了边缘居民，这是一种独特的挖掘机，专注于探索和绘制洞穴的外边缘。 当其他人可能犹豫不决时，边缘居民却大踏步前进，揭示了人迹罕至的道路和长期隐藏在洞穴僻静角落的秘密。",
    "Cave excavators learn to locate un-excavated tiles with increased efficiency using echolocation, leading to a significant enhancement in overall excavation progress. Echolocation will be used to locate a target if an excavator performs 15 moves without encountering excavatable tiles. Max. location discovery takes place in a 50x50 grid around the excavator.": "洞穴挖掘机学会使用回声定位来提高效率地定位未挖掘的瓷砖，从而显着提高整体挖掘进度。 如果挖掘机执行 15 次移动而没有遇到可挖掘的瓷砖，则将使用回声定位来定位目标。 最大限度。 位置发现发生在挖掘机周围 50x50 的网格中。",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "warmth (": "温暖 (",
    "energy (": "能量 (",
    "fibers (": "纤维 (",
    "nourishment (": "营养 (",
    "sludge (": "污泥 (",
    "biomites (": "生物螨 (",
    "zymers (": "酶 (",
    "Zymers:": "酶（z）：",
    "Warmth:": "温暖（w）：",
    "Sludge:": "污泥（s）：",
    "Information:": "信息（i）：",
    "Algae:": "藻类（a）：",
    "Nourishment:": "营养（n）：",
    "Biomites:": "生物螨（b）：",
    "Energy:": "能量（e）：",
    "Fibers:": "纤维（f）：",
    "Glow": "发光",
    "Grab": "抓住",
    "Energy": "能量（e）",
    "Information": "信息（i）",
    "Nourishment": "营养（n）",
    "Warmth": "温暖（w）",
    "Evolution": "进化",
    "Actions": "动作",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "Scientific": "科学计数法",
    "Standard": "标准",
    "Blind": "盲文",
    "Letters": "字母",
    "Mixed Engineering": "混合工程",
    "Mixed Scientific": "混合科学",
    "Chemistry": "化学",
    "Engineering": "工程符号",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    'i': 'i',
    'I': 'I',
    'II': 'I',
    'III': 'III',
    'IV': 'IV',
    'V': 'V',
    'VI': 'VI',
    'VII': 'VII',
    'VIII': 'VIII',
    'X': 'X',
    'XI': 'XI',
    'XII': 'XII',
    'XIII': 'XIII',
    'XIV': 'XIV',
    'XV': 'XV',
    'XVI': 'XVI',
    'A': 'A',
    'B': 'B',
    'C': 'C',
    'D': 'D',
    'E': 'E',
    'F': 'F',
    'G': 'G',
    'H': 'H',
    'I': 'I',
    'J': 'J',
    'K': 'K',
    'L': 'L',
    'M': 'M',
    'N': 'N',
    'O': 'O',
    'P': 'P',
    'Q': 'Q',
    'R': 'R',
    'S': 'S',
    'T': 'T',
    'U': 'U',
    'V': 'V',
    'W': 'W',
    'X': 'X',
    'Y': 'Y',
    'Z': 'Z',
    '<': '<',
    '<<': '<<',
    '>': '>',
    '>>': '>>',
    'a': 'a',
    'b': 'b',
    'c': 'c',
    'd': 'd',
    'e': 'e',
    'f': 'f',
    'g': 'g',
    'h': 'h',
    'i': 'i',
    'j': 'j',
    'k': 'k',
    'l': 'l',
    'm': 'm',
    'n': 'n',
    'o': 'o',
    'p': 'p',
    'q': 'q',
    'r': 'r',
    's': 's',
    't': 't',
    'u': 'u',
    'v': 'v',
    'w': 'w',
    'x': 'x',
    'y': 'y',
    'z': 'z',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀，此处可以截取语句开头部分的内容进行汉化
//例如：Coin: 13、Coin: 14、Coin: 15... 这种有相同开头的语句
//可以在这里汉化开头："Coin: ":"金币: "
var cnPrefix = {
    "\n": "\n",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": " ",
    " ": " ",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Title: ": "标题：",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Notation: ": "符号: ",
    "Toggle Music: ": "切换声音: ",
    "Radiators (cost: ": "散热器（成本：",
    "Suction Cups (cost: ": "吸盘（成本：",
    "Synaptic Glacialis (cost: ": "突触冰（成本：",
    "Spikes (cost: ": "尖峰（成本：",
    "Sensory Pulsars (cost: ": "感官脉冲星（成本：",
    "Resonance Tendrils (cost: ": "共振卷须（成本：",
    "Mitochondria (cost: ": "线粒体（成本：",
    "Monotrichous Flagella (cost: ": "单毛鞭毛（成本：",
    "Membrane Thickness (cost: ": "膜厚度（成本：",
    "Lophotrichous Flagella (cost: ": "丛鞭毛（成本：",
    "Endoplasmic Reticulum (cost: ": "内质网（成本：",
    "Feathered Antenna (cost: ": "羽毛天线（成本：",
    "Echo Chamber (cost: ": "共鸣室（成本：",
    "Calorimetric Granulum (cost: ": "量热颗粒（成本：",
    "Nucleus (cost: ": "细胞核（成本：",
    "Sensors (cost: ": "传感器（成本：",
    "Grow Tendon (": "长肌腱 (",
    "Swamp: ": "沼泽：",
    "Land: ": "陆地: ",
    "Flower: ": "花: ",
    "Wave: ": "波涛: ",
    "Solara: ": "太阳: ",
    "Snow cap: ": "雪冠: ",
    "Muddy patch: ": "泥泞地: ",
    "Sand dune: ": "沙丘: ",
    "Rocky outcrop: ": "露头的岩石: ",
    "Salt flat: ": "盐滩: ",
    "Reed: ": "芦苇: ",
    "Ice cave: ": "冰洞: ",
    "Pebble: ": "卵石: ",
    "Mountain: ": "山川: ",
    "Desert: ": "沙漠: ",
    "Crystal: ": "水晶: ",
    "Forest: ": "森林: ",
    "Water: ": "水: ",
    "Icy land: ": "冰原: ",
    "Generates: ": "生成：",
    "The First Starlight": "第一缕星光",
    "Volcano: ": "火山: ",
    "Fungi: ": "真菌: ",
    "River: ": "河流: ",
    "Rock: ": "石头: ",
    "Oasis: ": "绿洲: ",
    "Advanced Tunneling ": "高级隧道 ",
    "Harmonic Symbiosis ": "和谐共生 ",
    "Memory Imprints ": "记忆印记 ",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀，此处可以截取语句结尾部分的内容进行汉化
//例如：13 Coin、14 Coin、15 Coin... 这种有相同结尾的语句
//可以在这里汉化结尾：" Coin":" 金币"
var cnPostfix = {
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "/sec)": "/秒)",
    "e)": "能量)",
    "n)": "营养)",
    "w)": "温暖)",
    "Maxed out)": "最大值）",
    " (Completed)": "（已完成）",
    " [Research]": " [研究]",
    " [Evolution]": " [进化]",
    " [Exploration]": " [探索]",
    " [New Mechanic]": " [新机制]",
    " [Action]": " [动作]",
    " [Solara]": " [太阳]",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^\$([\d\.]+)$/,
    /^\(([\d\.]+)\)$/,
    /^([\d\.]+)\%$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.,]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^成本(.+)$/,
    /^解锁(.+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+) T$/,
    /^([\d\.]+) Qi$/,
    /^([\d\.]+) Qa$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^\$([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+) \/ ([\d\.]+)e([\d\.,]+)$/,
    /^\$([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e\+([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
    [/^Row: (.+) Progress: (.+) SP: (.+)$/, '行: $1 进度: $2 太阳点数(SP): $3'],
    [/^(.+) generation bonus for sludge and algae.$/, '$1 生成奖励对于污泥和藻类。'],
    [/^\(cost: (.+)n (.+)i\)$/, '（成本：$1营养 $2信息）'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^\+([\d\.,]+) Prestige Point$/, '\+$1 声望点'],
    [/^([\d\.,]+) cells per division$/, '$1 每次分裂的细胞数'],
    [/^([\d\.,]+) Land tiles.$/, '$1 陆地地块'],
    [/^([\d\.,]+) Water tiles.$/, '$1 水地块'],
    [/^([\d\.,]+) information.$/, '$1 信息。'],
    [/^([\d\.,]+)K information.$/, '$1K 信息。'],
    [/^([\d\.,]+)K cells.$/, '$1K 细胞。'],
    [/^([\d\.,]+) information$/, '$1 信息'],
    [/^([\d\.,]+) information, ([\d\.,]+) warmth$/, '$1 信息，$2 温暖'],
    [/^([\d\.,]+) information, ([\d\.,]+) nourishment.$/, '$1 信息，$2 营养。'],
    [/^([\d\.,]+) information, ([\d\.,]+) warmth, and ([\d\.,]+) sludge$/, '$1 信息，$2 温暖，以及 $3 污泥'],
    [/^([\d\.,]+) information, ([\d\.,]+) biomites, ([\d\.,]+) sludge.$/, '$1 信息，$2 生物螨, $3 污泥。'],
    [/^([\d\.,]+) information, ([\d\.,]+) biomites, ([\d\.,]+) zymers, ([\d\.,]+) sludge$/, '$1 信息，$2 生物螨, $3 酶, $4 污泥'],
    [/^([\d\.,]+) information, ([\d\.,]+) biomites, ([\d\.,]+) zymers, ([\d\.,]+) fibers, ([\d\.,]+) algae$/, '$1 信息，$2 生物螨, $3 酶，$4 纤维，$5 藻类。'],
    [/^([\d\.,]+) information, ([\d\.,]+) biomites, ([\d\.,]+) zymers, ([\d\.,]+) fibers, ([\d\.,]+) sludge, ([\d\.,]+) algae.$/, '$1 信息，$2 生物螨, $3 酶，$4 纤维，$5 污泥，$6 藻类。'],
    [/^([\d\.,]+) Water tiles, Discovery of Pebble.$/, '$1 水地块，发现卵石。'],
    [/^([\d\.,]+) Desert tiles, ([\d\.,]+) water tiles.$/, '$1 沙漠地块，$2 水地块。'],
    [/^([\d\.,]+)n ([\d\.,]+)$/, '$1营养 $2'],
    [/^([\d\.,]+)b ([\d\.,]+)z\)$/, '$1生物螨 $2酶\)'],
    [/^([\d\.,]+)s, ([\d\.,]+)a\)$/, '$1污泥, $2藻类\)'],
    [/^([\d\.,]+)n ([\d\.,]+)i\)$/, '$1营养 $2信息\)'],
    [/^([\d\.,]+)n ([\d\.,]+)i ([\d\.,]+)$/, '$1营养 $2信息 $3'],
    [/^([\d\.,]+)n ([\d\.,]+)w ([\d\.,]+)$/, '$1营养 $2温暖 $3'],
    [/^([\d\.,]+)n ([\d\.,]+)i ([\d\.,]+)w ([\d\.,]+)$/, '$1营养 $2信息 $3温暖 $4'],
    [/^([\d\.,]+)n ([\d\.,]+)i ([\d\.,]+)w (.+)$/, '$1营养 $2信息 $3温暖 $4'],
    [/^Day ([\d\.,]+)$/, '天数 $1'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Cost: (.+) SP$/, '成本：$1 太阳点数(SP)'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);